### GET all
GET http://localhost:3535/auth
Content-Type: application/json

### GET by ID
GET http://localhost:3535/auth/1

### Add user
POST http://localhost:3535/auth/signup
Content-Type: application/json

{
  "email": "helsdsdsdfsdflo@dhhsssdsdsds.com",
  "password": "2343sseed"
}


### Reports

### Create report
POST http://localhost:3535/reports
Content-Type: application/json

{
  "title": "title",
  "content": "content",
  "secret": "secret"
}

### Get all reports
GET http://localhost:3535/reports

### Get report by ID
GET http://localhost:3535/reports/1
